# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x1a\x1bgoogle/protobuf/empty.proto\"$\n\x0c\x41\x64\x64NumberReq\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x19\n\x0c\x41\x64\x64NumberRes\x12\t\n\x01\x61\x18\x01 \x01(\x05\"\x1a\n\rReadFromDBRes\x12\t\n\x01\x61\x18\x01 \x01(\x05\x32m\n\x06Server\x12+\n\tAddNumber\x12\r.AddNumberReq\x1a\r.AddNumberRes\"\x00\x12\x36\n\nReadFromDB\x12\x16.google.protobuf.Empty\x1a\x0e.ReadFromDBRes\"\x00\x42\x06Z\x04./pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _ADDNUMBERREQ._serialized_start=45
  _ADDNUMBERREQ._serialized_end=81
  _ADDNUMBERRES._serialized_start=83
  _ADDNUMBERRES._serialized_end=108
  _READFROMDBRES._serialized_start=110
  _READFROMDBRES._serialized_end=136
  _SERVER._serialized_start=138
  _SERVER._serialized_end=247
# @@protoc_insertion_point(module_scope)
