# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import server_pb2 as server__pb2


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddNumber = channel.unary_unary(
                '/Server/AddNumber',
                request_serializer=server__pb2.AddNumberReq.SerializeToString,
                response_deserializer=server__pb2.AddNumberRes.FromString,
                )
        self.ReadFromDB = channel.unary_unary(
                '/Server/ReadFromDB',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=server__pb2.ReadFromDBRes.FromString,
                )


class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFromDB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNumber,
                    request_deserializer=server__pb2.AddNumberReq.FromString,
                    response_serializer=server__pb2.AddNumberRes.SerializeToString,
            ),
            'ReadFromDB': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFromDB,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=server__pb2.ReadFromDBRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Server/AddNumber',
            server__pb2.AddNumberReq.SerializeToString,
            server__pb2.AddNumberRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadFromDB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Server/ReadFromDB',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            server__pb2.ReadFromDBRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
